# 카테고리 상의를 클릭했을 때 조회하는 쿼리 
SELECT * FROM PRODUCT WHERE PR_CA_NUM = 1;

SELECT * FROM PRODUCT 
WHERE PR_CA_NUM = (SELECT CA_NUM FROM CATEGORY WHERE CA_NAME = '상의');

SELECT * FROM PRODUCT JOIN CATEGORY ON CA_NUM = PR_CA_NUM
WHERE CA_NAME = '상의';

SELECT * FROM PRODUCT 
WHERE PR_CA_NUM = (SELECT CA_NUM FROM CATEGORY WHERE CA_CODE = 'TOP');

SELECT * FROM PRODUCT
WHERE PR_CODE LIKE CONCAT('TOP', '%');

# abc123회원이 구매한 제품들 목록을 조회하는 쿼리 
SELECT DISTINCT PRODUCT.* FROM BUY 
JOIN BUY_LIST ON BU_NUM = BL_BU_NUM
JOIN PRODUCT ON PR_CODE = BL_PR_CODE 
WHERE BU_ME_ID = 'abc123';


